from aegisx.core.models import default_model
from typing import Dict, Any, List
import uuid
import asyncio
from pydantic import BaseModel, Field
from pydantic_ai import Agent
from aegisx.agents.base import BaseAgent
from aegisx.core.schemas.findings import Finding
from aegisx.core.runtime_governor import RuntimeGovernor, ScanMode
from aegisx.core.ui.console import ConsoleUI
import os
from pathlib import Path

# Ensure environment variables are loaded for API Keys
env_path = Path(os.getcwd()) / ".env"
if env_path.exists():
    with open(env_path, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                k, v = line.split('=', 1)
                os.environ[k] = v
                if k == 'OPENROUTER_API_KEY':
                    os.environ['GOOGLE_API_KEY'] = v

class ValidationAction(BaseModel):
    """Specific contextual test generated by AI."""
    endpoint: str = Field(..., description="Endpoint to validate")
    test_type: str = Field(..., description="Type of validation (e.g., Auth Bypass, IDOR, SQLi)")
    reasoning: str = Field(..., description="Why this test is contextually relevant")
    requires_fuzzing: bool = Field(default=False, description="Whether this specific test requires fuzzing")

class ValidationStrategy(BaseModel):
    """The overall strategy for validating the target."""
    reasoning: str = Field(..., description="Overall reasoning based on semantic discovery")
    nuclei_tags_to_run: List[str] = Field(
        ..., 
        description="Specific Nuclei tags to safely execute based on the target context (e.g., ['cve', 'exposure', 'expressjs', 'api']). MUST EXCLUDE fuzzing or dast tags unless absolutely necessary."
    )
    actions: List[ValidationAction] = Field(..., description="List of targeted actions to perform")

validation_ai = Agent(
    default_model,
    output_type=ValidationStrategy,
    system_prompt=(
        "You are the AEGIS-X Adaptive Validation Engine. "
        "You will receive semantic discovery insights (frameworks, API styles, inferred endpoints, trust boundaries). "
        "Your job is to generate a small set of highly targeted validation actions AND a real-time execution plan for active scanners like Nuclei. "
        "For 'nuclei_tags_to_run', prescribe ONLY the most relevant, non-destructive tags based on the target's specific frameworks and API styles. "
        "DO NOT default to fuzzing. Fuzzing should only be recommended if there is explicit evidence "
        "warranting it (e.g., a specific hidden parameter discovered in JS). "
        "Focus on context-aware validation."
    )
)

class AdaptiveValidationEngine(BaseAgent):
    """
    Decides what to scan and how, based on semantic discovery.
    Replaces the unconditional 15-scanner execution unless in DEEP_ANALYSIS mode.
    """
    
    def __init__(self):
        super().__init__(agent_id="AdaptiveValidationEngine")
        
    async def process(self, state: Dict[str, Any]) -> Dict[str, Any]:
        target = state.get("target")
        self.log_action("start_adaptive_validation", {"target": target})
        
        gov = RuntimeGovernor.instance()
        
        frameworks = state.get("frameworks", [])
        api_style = state.get("api_style", "Unknown")
        inferred_endpoints = state.get("inferred_endpoints", [])
        trust_boundaries = state.get("trust_boundaries", [])
        
        context_block = f"""
        Target: {target}
        Frameworks: {', '.join(frameworks)}
        API Style: {api_style}
        Inferred Endpoints: {', '.join(inferred_endpoints)}
        Trust Boundaries: {', '.join(trust_boundaries)}
        """
        
        try:
            result = await validation_ai.run(f"Generate an adaptive validation strategy for this context:\n{context_block}")
            strategy: ValidationStrategy = result.output
            
            self.log_action("validation_strategy_generated", {
                "actions_count": len(strategy.actions),
                "reasoning": strategy.reasoning
            })
            
            ConsoleUI.info(f"[AdaptiveValidation] Strategy: {strategy.reasoning}")
            ConsoleUI.info(f"[AdaptiveValidation] Prescribed Nuclei Tags: {', '.join(strategy.nuclei_tags_to_run)}")
            
            # Filter actions if we shouldn't fuzz
            actions_to_run = []
            for action in strategy.actions:
                if action.requires_fuzzing and gov.mode != ScanMode.DEEP_ANALYSIS:
                    ConsoleUI.warning(f"[AdaptiveValidation] Skipping fuzzing action due to mode constraint: {action.test_type} on {action.endpoint}")
                else:
                    actions_to_run.append(action)
                    ConsoleUI.success(f"[AdaptiveValidation] Scheduled validation: {action.test_type} on {action.endpoint}")
            
            # Inject the AI's execution plan into the state for downstream tools
            if "tool_execution_plan" not in state:
                state["tool_execution_plan"] = {}
            state["tool_execution_plan"]["nuclei_tags"] = strategy.nuclei_tags_to_run
            
            return {
                "phase": "adaptive_validation_complete",
                "validation_actions": [a.model_dump() for a in actions_to_run],
                "tool_execution_plan": state["tool_execution_plan"]
            }
            
        except Exception as e:
            self.log_action("adaptive_validation_failed", {"error": str(e)})
            return {"phase": "adaptive_validation_failed", "error": str(e)}
