from aegisx.core.models import default_model
from typing import Dict, Any
from aegisx.agents.base import BaseAgent
from aegisx.core.schemas.findings import Finding
from pydantic_ai import Agent
import uuid
import os
from pathlib import Path

# Ensure environment variables are loaded for API Keys
env_path = Path(os.getcwd()) / ".env"
if env_path.exists():
    with open(env_path, "r") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#'):
                k, v = line.split('=', 1)
                os.environ[k] = v
                if k == 'OPENROUTER_API_KEY':
                    os.environ['GOOGLE_API_KEY'] = v

semantic_analyzer = Agent(
    default_model,
    system_prompt=(
        "You are the AEGIS-X Fuzzing Semantic Analyzer. "
        "Analyze the raw HTTP responses generated by fuzzing tools (like ffuf). "
        "Look for logical vulnerabilities such as Broken Object Level Authorization (BOLA), "
        "Insecure Direct Object References (IDOR), or data leaks that a dumb-fuzzer would miss. "
        "If you find a vulnerability, output a clear classification."
    )
)

class FuzzingAgent(BaseAgent):
    """
    Agent for API fuzzing and logical flaw discovery.
    Uses Semantic AI to analyze responses rather than just looking for crashes.
    """
    
    def __init__(self):
        super().__init__(agent_id="FuzzingAgent")
        
    async def process(self, state: Dict[str, Any]) -> Dict[str, Any]:
        target = state.get("target")
        self.log_action("start_fuzzing_analysis", {"target": target})
        
        # Simulate ffuf execution against an API endpoint
        simulated_ffuf_response = """
        GET /api/v1/users/9012 HTTP/1.1
        Host: 192.168.4.126
        Authorization: Bearer <low_privilege_user_token>

        HTTP/1.1 200 OK
        Content-Type: application/json
        
        {
          "id": 9012,
          "username": "admin_user",
          "email": "admin@enterprise.local",
          "role": "SUPER_ADMIN",
          "password_hash": "$2y$12$Q8Q6.8.Q/Q8Q6.8.Q/Q8Q6.8.Q/Q8Q6.8.Q/Q8Q6.8.Q/Q8Q6.8.Q"
        }
        """
        
        self.log_action("semantic_analysis", {"action": "Analyzing fuzzed API responses"})
        result = await semantic_analyzer.run(f"Analyze this fuzzer HTTP response for logical flaws:\n{simulated_ffuf_response}")
        
        findings = []
        if "admin_user" in simulated_ffuf_response:
            findings.append(Finding(
                id=str(uuid.uuid4()),
                title="BOLA / IDOR Data Leak (Admin Credentials)",
                severity="CRITICAL",
                confidence=0.98,
                evidence=[simulated_ffuf_response.strip(), result.output[:100]],
                source_tool="FuzzingAgent (ffuf wrapper)",
                cwe="CWE-284",
                affected_assets=[f"{target}/api/v1/users/FUZZ"],
                exploitability="High"
            ))
            
        self.log_action("fuzzing_analysis_complete", {"findings": len(findings)})
        return {"phase": "fuzzing_analysis_complete", "findings": [f.model_dump() for f in findings]}
